stateDict = {
    '0': "Alabama",
    '1': "Alaska",
    '2': "Arizona",
    '3': "Arkansas",
    '4': "California",
    '5': "Colorado",
    '6': "Connecticut",
    '7': "Delaware",
    '8': "District of Columbia",
    '9': "Florida",
    '10': "Georgia",
    '11': "Guam",
    '12': "Hawaii",
    '13': "Idaho",
    '14': "Illinois",
    '15': "Indiana",
    '16': "Iowa",
    '17': "Kansas",
    '18': "Kentucky",
    '19': "Louisiana",
    '20': "Maine",
    '21': "Maryland",
    '22': "Massachusetts",
    '23': "Michigan",
    '24': "Minnesota",
    '25': "Mississippi",
    '26': "Missouri",
    '27': "Montana",
    '28': "Nebraska",
    '29': "Nevada",
    '30': "New Hampshire",
    '31': "New Jersey",
    '32': "New Mexico",
    '33': "New York",
    '34': "North Carolina",
    '35': "North Dakota",
    '36': "Northern Mariana Islands",
    '37': "Ohio",
    '38': "Oklahoma",
    '39': "Oregon",
    '40': "Pennsylvania",
    '41': "Puerto Rico",
    '42': "Rhode Island",
    '43': "South Carolina",
    '44': "South Dakota",
    '45': "Tennessee",
    '46': "Texas",
    '47': "Utah",
    '48': "Vermont",
    '49': "Virgin Islands",
    '50': "Virginia",
    '51': "Washington",
    '52': "West Virginia",
    '53': "Wisconsin",
    '54': "Wyoming"
}
